### PR TITLE
added severity to CLI output

### LINKED ISSUE #22: Update CLI to output severity
It would be helpful for CI/CD if the `custom_lint` CLI output the severity of the lint. For example, perhaps I want to fail PR's that trigger a lint of 'error' severity, but don't want to fail it for 'warning' or 'info' lints.

### PR DESCRIPTION
**Pull request by AdamNSmith**
fixes #22

### CODE REVIEW

**Comment by rrousselGit** [comment]
Thanks a lot! Could you update the tests accordingly?

**Comment by AdamNSmith** [comment]
I'm happy to update it! I'm new to contributing to this repo, so I'm sure I'm just missing something obvious, but whenever I try to run tests with `dart test` from the 'dart_custom_lint/packages/custom_lint' directory, I get a whole host of errors saying that it can't find the correct files. Here's one example:
CleanShot 2022-08-16 at 16 33 53

What am I missing?

**Comment by rrousselGit** [comment]
It sounds like you're missing a "pub get" in those projects

**Comment by AdamNSmith** [comment]
Thanks for the reply. I've tried that and the issue remains. The problem appears to be an incorrect path. The error message is saying that it's looking for 'package_config.json' at
`/Users/Smith/Developer/mobile/dart_custom_lint/packages/example_lint/.dart_tool/package_config.json`

when in reality it exists at
`/Users/Smith/Developer/mobile/dart_custom_lint/packages/custom_lint/example/example_lint/.dart_tool/package_config.json`

Is there an environment variable that I need to set perhaps? Or a different directory to run the tests from? I'm simply trying to run `dart test` from the 'dart_custom_lint/packages/custom_lint' directory.

**Comment by rrousselGit** [comment]
Could be a bug. The path you've described used to be correct, but we moved the example afterward.

Feel free to change the path :)
That should hopefully be a simple fix

**Comment by AdamNSmith** [comment]
Sounds good -- I'll work on that. Just wanted to make sure I wasn't missing something before making that change.

**Comment by rrousselGit** [comment]
It's hard to say without tests. Tests help the review process, as they help conceptualize what's actually added

**Comment by AdamNSmith** [comment]
I fixed the paths to the tests, so now some of the tests run, but most still fail (14/17 tests still fail).

**Pull request closed without merging**
